const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');
const BaseService = require('./base');
const platform = require('../utils/platform');
const logger = require('../utils/logger');
const { detectPHP } = require('../installer/detector');

class PHPService extends BaseService {
  constructor() {
    super('php', {});
  }

  detect() {
    return this.getInstallPath();
  }

  getInstallPath() {
    return detectPHP();
  }

  getPhpDir() {
    const binPath = this.getInstallPath();
    return binPath ? path.dirname(binPath) : null;
  }

  getExtDir() {
    const phpDir = this.getPhpDir();
    if (!phpDir) return null;
    const candidates = [
      path.join(phpDir, 'ext'),
      path.join(phpDir, 'lib', 'php', 'extensions'),
      path.join(phpDir, '..', 'lib', 'php', 'extensions')
    ];
    for (const c of candidates) {
      if (fs.existsSync(c)) return c;
    }
    return path.join(phpDir, 'ext');
  }

  getPhpIniPath() {
    const iniPath = platform.phpIniFile;
    this.ensurePhpIni();
    return iniPath;
  }

  ensurePhpIni() {
    const iniPath = platform.phpIniFile;
    const iniDir = path.dirname(iniPath);
    if (!fs.existsSync(iniDir)) fs.mkdirSync(iniDir, { recursive: true });

    const extDir = this.getExtDir();
    const extDirFormatted = extDir ? extDir.replace(/\\/g, '/') : 'ext';

    // Build optimized php.ini
    const iniContent = `[PHP]
;; Generated by LocalXWeb for optimal development
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = -1
zend.enable_gc = On

;; Resource Limits
max_execution_time = 300
max_input_time = 60
memory_limit = 512M

;; Error handling and logging
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = On
display_startup_errors = On
log_errors = On
error_log = "${path.join(platform.logsDir, 'php_errors.log').replace(/\\/g, '/')}"

;; Data Handling
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
post_max_size = 128M

;; File Uploads
file_uploads = On
upload_max_filesize = 128M
max_file_uploads = 20

;; Module Settings
default_mimetype = "text/html"
default_charset = "UTF-8"

;; Extension Directory
extension_dir = "${extDirFormatted}"

;; Enabled Extensions
${platform.isWindows ? `
extension=bz2
extension=curl
extension=fileinfo
extension=gd
extension=gettext
extension=intl
extension=mbstring
extension=exif
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=soap
extension=sockets
extension=sqlite3
extension=tidy
extension=xsl
extension=zip
` : `
extension=curl
extension=fileinfo
extension=gd
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
`}

[Date]
date.timezone = UTC

[MySQLi]
mysqli.max_persistent = -1
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.default_port = 3306
mysqli.default_socket =
mysqli.default_host = 127.0.0.1
mysqli.default_user = root
mysqli.default_pw =
mysqli.reconnect = Off

[Session]
session.save_handler = files
session.save_path = "${path.join(platform.localxwebDir, 'tmp').replace(/\\/g, '/')}"
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.cache_limiter = nocache
session.cache_expire = 180
`.trim();

    fs.writeFileSync(iniPath, iniContent);
    return iniPath;
  }

  getExecutionCommand(args = []) {
    const bin = this.getInstallPath();
    if (!bin) return null;
    const ini = this.getPhpIniPath();
    return {
      bin,
      args: ['-c', ini, ...args]
    };
  }

  async status() {
    const phpPath = this.getInstallPath();
    if (!phpPath) return 'not installed';
    return 'installed';
  }

  async start() {
    logger.info('PHP is ready (executes via Apache mod_php or phpMyAdmin server)');
    return true;
  }

  async stop() {
    return true;
  }

  getVersion() {
    const phpPath = this.getInstallPath();
    if (!phpPath) return null;
    try {
      return execSync(`"${phpPath}" -v`, { encoding: 'utf8' }).split('\n')[0].trim();
    } catch {
      return null;
    }
  }

  getLoadedExtensions() {
    const cmd = this.getExecutionCommand(['-m']);
    if (!cmd) return [];
    try {
      const output = execSync(`"${cmd.bin}" ${cmd.args.map(a => `"${a}"`).join(' ')}`, {
        encoding: 'utf8'
      });
      return output.split('\n')
        .map(l => l.trim())
        .filter(l => l && !l.startsWith('['));
    } catch {
      return [];
    }
  }

  async install(onProgress) {
    const packageManager = require('../installer/packageManager');
    return packageManager.installService('php', this, onProgress);
  }

  getDownloadUrl() {
    if (platform.isWindows) {
      return 'https://windows.php.net/downloads/releases/php-8.3.16-Win32-vs16-x64.zip';
    }
    return null;
  }
}

module.exports = PHPService;
